In [3]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import time

In [5]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
print(f"{STUDENT_NAME}'s Array:", data) 
 
mean_val = np.mean(data) 
std_val = np.std(data) 
print("Mean:", mean_val, "Std Dev:", std_val) 


Arjames E Kinilitan's Array: [60 10 14 43  9 51 59  4 48  8]
Mean: 30.6 Std Dev: 22.2


In [6]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
print(f"{STUDENT_NAME}'s Matrix:\n", matrix) 
 
row_sums = np.sum(matrix, axis=1) 
col_sums = np.sum(matrix, axis=0) 
print("Row sums:", row_sums) 
print("Column sums:", col_sums) 


Arjames E Kinilitan's Matrix:
 [[10  7 14  9]
 [ 4  8 16  9]
 [ 1 21 20 29]]
Row sums: [40 37 71]
Column sums: [15 36 50 47]


In [7]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3)) 
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d) 
 
slice_mid = arr3d[:,1,:] 
print("Slice[:,1,:]:\n", slice_mid) 


Arjames E Kinilitan's 3D Array:
 [[[ 9  6 13]
  [10  8 18]
  [26  3 15]]

 [[ 7 15  8]
  [ 0  8  6]
  [20 19  9]]

 [[ 2 26  4]
  [26  3 13]
  [17  7 18]]]
Slice[:,1,:]:
 [[10  8 18]
 [ 0  8  6]
 [26  3 13]]


In [8]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)] 
print(f"{STUDENT_NAME}'s Original:", x) 
print("Filtered subset:", filtered) 


Arjames E Kinilitan's Original: [60 10 14 43  9 51 59  4 48  8]
Filtered subset: []


In [9]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A) 
print("Matrix B:\n", B) 
 
product = A @ B 
det_A = np.linalg.det(A) 
print("A @ B:\n", product) 
print("Determinant of A:", det_A) 


Matrix A:
 [[10  7]
 [14  9]]
Matrix B:
 [[ 4  8]
 [16  9]]
A @ B:
 [[152 143]
 [200 193]]
Determinant of A: -8.000000000000009


In [10]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017  
 
angles = np.linspace(0, 2*np.pi, 8) 
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles) 

print(f"{STUDENT_NAME}'s Angles:", angles) 
print("Sine:", sine_vals) 
print("Cosine:", cos_vals) 


Arjames E Kinilitan's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [11]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0 
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr) 


Arjames E Kinilitan's Modified 4x4 Array:
 [[ 0  7  0  9]
 [ 4  8 16  9]
 [ 0 21  0 29]
 [ 3 36 14  8]]


In [12]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017  
 
np.random.seed(STUDENT_ID) 
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10) 
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')

print(f"{STUDENT_NAME}'s Scores:", scores) 
print("Grades:", grades) 


Arjames E Kinilitan's Scores: [59  9 13 42  8 50 58  3 47  7]
Grades: ['Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Fail' 'Fail' 'Fail']


In [13]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
flat_arr = arr.flatten() 
transposed_arr = arr.T 

print("Original array:\n", arr) 
print("Flattened:", flat_arr) 
print("Transposed:\n", transposed_arr) 


Original array:
 [[10  7 14  9]
 [ 4  8 16  9]
 [ 1 21 20 29]]
Flattened: [10  7 14  9  4  8 16  9  1 21 20 29]
Transposed:
 [[10  4  1]
 [ 7  8 21]
 [14 16 20]
 [ 9  9 29]]


In [14]:
import numpy as np 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3)) 
mask = arr % 2 == 0 
arr[mask] = -1 

print("Array with conditional replacements:\n", arr) 


Array with conditional replacements:
 [[-1  7 -1]
 [ 9 -1 -1]
 [-1  9  1]]


In [15]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
STUDENT_ID%100+50,5), 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
print(df) 


                  Name  Score  YearsCodePro
0  Arjames E Kinilitan     26            18
1  Arjames E Kinilitan     23            26
2  Arjames E Kinilitan     30             3
3  Arjames E Kinilitan     59            15
4  Arjames E Kinilitan     25             7


In [16]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
STUDENT_ID%100+50,5), 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
print(df) 

                  Name  Score  YearsCodePro
0  Arjames E Kinilitan     26            18
1  Arjames E Kinilitan     23            26
2  Arjames E Kinilitan     30             3
3  Arjames E Kinilitan     59            15
4  Arjames E Kinilitan     25             7


In [18]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'], 
    # Corrected to use a functional salary range, e.g., 40000 to 150000 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean() 
print(avg_salary) 


EdLevel
Bachelor    145572.0
Master       90073.5
PhD          86534.0
Name: ConvertedComp, dtype: float64


In [19]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
top5 = df.sort_values(by='ConvertedComp', ascending=False) 
print(top5) 


       Country  ConvertedComp
0  Philippines         148091
3       Canada         143053
4      Germany          97130
2           UK          86534
1          USA          83017


In [20]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name':[STUDENT_NAME]*5, 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 

high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp) 


                  Name  YearsCodePro
0  Arjames E Kinilitan             9
2  Arjames E Kinilitan            13
3  Arjames E Kinilitan            10
4  Arjames E Kinilitan             8


In [21]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)}) 
 
bins = [0, 50000, 100000, 150000, 200000] 
labels = ['0-50k', '50-100k', '100-150k', '>150k'] 
 
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels) 
print(df) 


   ConvertedComp   Bracket
0         148091  100-150k
1          83017   50-100k
2          86534   50-100k
3         143053  100-150k
4          97130   50-100k


In [22]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017
 
np.random.seed(STUDENT_ID) 
 
# Original Code Issue:  
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)  # -> np.random.randint(12345, 12345, 5) which is a zero-length range. 
 
# Corrected Code: Using a functional salary range (40000 to 150000) df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)}) 
 
df['LogComp'] = np.log(df['ConvertedComp']) 
print(df) 


   ConvertedComp   Bracket    LogComp
0         148091  100-150k  11.905582
1          83017   50-100k  11.326801
2          86534   50-100k  11.368293
3         143053  100-150k  11.870970
4          97130   50-100k  11.483806


In [23]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5), 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
corr_matrix = df.corr() 
print(corr_matrix) 


               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.120283
ConvertedComp      0.120283       1.000000


In [24]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)



    EdLevel      mean    median          std
0  Bachelor  145572.0  145572.0  3562.403964
1    Master   90073.5   90073.5  9979.398003
2       PhD   86534.0   86534.0          NaN


In [25]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017  
 
np.random.seed(STUDENT_ID) 
 
# Generate salaries: [100727, 136195, 130612, 100727, 95233] df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)}) 
 
threshold = 110000 
 
# Create the 'HighPay' column using np.where() 
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No') 
 
print(df)


    EdLevel  ConvertedComp HighPay
0  Bachelor         148091     Yes
1    Master          83017      No
2       PhD          86534      No
3  Bachelor         143053     Yes
4    Master          97130      No


In [26]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Arjames E Kinilitan" 
STUDENT_ID = 2017 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5) 
}) 
 
# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

# ...code above...
top_countries


,mean,max
Country,,
Canada,143053.0,143053
Germany,97130.0,97130
Philippines,148091.0,148091
UK,86534.0,86534
USA,83017.0,83017


In [1]:
import pandas as pd
import numpy as np

# 1. Configuration & Identification
student_id = 2017
last_three_digits = 17  # Last three digits: 017
filename = 'programming_languages_popularity.csv'

# 2. Load and Prepare Data
df_raw = pd.read_csv(filename)
date_col = df_raw.columns[0]
df_raw[date_col] = pd.to_datetime(df_raw[date_col])

# 3. Determine Assigned Language
# Sort language columns alphabetically (excluding the date column)
languages = sorted([col for col in df_raw.columns if col != date_col])
num_languages = len(languages)
assigned_index = last_three_digits % num_languages
assigned_language = languages[assigned_index]

# 4. Data Extraction
df = df_raw[[date_col, assigned_language]].copy()
df.columns = ['Month', 'Popularity']

# 5. Calculations: Growth Rate and Rolling Stats
df['Growth_Rate'] = df['Popularity'].pct_change() * 100
df['Moving_Avg'] = df['Popularity'].rolling(window=12).mean()
df['Moving_STD'] = df['Popularity'].rolling(window=12).std()

# 6. Classify Growth Phases (Using NumPy Conditional Logic)
conditions = [
    (df['Growth_Rate'] > 5),
    (df['Growth_Rate'] < -5),
    (df['Growth_Rate'].notnull())
]
choices = ['Growth', 'Decline', 'Stable']
df['Phase'] = np.select(conditions, choices, default="N/A")

# 7. Statistical Summary & Key Metrics
summary = df['Popularity'].describe()
initial_pop = df['Popularity'].iloc[0]
final_pop = df['Popularity'].iloc[-1]
overall_growth = ((final_pop - initial_pop) / initial_pop) * 100
phase_counts = df['Phase'].value_counts()

# Output Results
print(f"Assigned Language: {assigned_language}")
print("-" * 30)
print("\nMain Analysis DataFrame (First 5 Rows):")
print(df.head())

print("\nStatistical Summary Table:")
print(summary)

print("\nGrowth Phase Counts:")
print(phase_counts)

print("\nKey Performance Metrics:")
print(f"- Initial Popularity: {initial_pop:.2f}")
print(f"- Final Popularity: {final_pop:.2f}")
print(f"- Overall Growth Percentage: {overall_growth:.2f}%")
print(f"- Periods: {len(df)}")

FileNotFoundError: [Errno 2] No such file or directory: 'programming_languages_popularity.csv'

In [2]:
import os
print("Current Folder:", os.getcwd())
print("Files I can see:", os.listdir())

Current Folder: c:\Users\Reno\Lab3_Functions_Kinilitan
Files I can see: ['.git', '.gitignore', '.venv', 'Activity_lab5_.txt', 'Activity_lab5_Additional Exercises.ipynb', 'Activity_lab6.ipynb', 'Activity_lab7.ipynb', 'Data_Lab.ipynb', 'density_evolution.gif', 'grades.py', 'lab3.py', 'Lab3_Functions_Kinilitan.ipynb', 'main.py', 'README.md', '__pycache__']


In [1]:
import pandas as pd
import numpy as np

# 1. Configuration & Identification
student_id = 2017
last_three_digits = 17 
# Updated filename based on your Most Popular Programming Languages.csv file
filename = 'Most Popular Programming Languages.csv' 

try:
    # 2. Load and Prepare Data
    df_raw = pd.read_csv(filename)
    date_col = df_raw.columns[0]
    df_raw[date_col] = pd.to_datetime(df_raw[date_col])

    # 3. Determine Assigned Language
    # Sort language columns alphabetically (excluding the date column)
    languages = sorted([col for col in df_raw.columns if col != date_col])
    num_languages = len(languages)
    assigned_index = last_three_digits % num_languages
    assigned_language = languages[assigned_index]

    # 4. Data Extraction
    df = df_raw[[date_col, assigned_language]].copy()
    df.columns = ['Month', 'Popularity']

    # 5. Calculations: Growth Rate and Rolling Stats
    df['Growth_Rate'] = df['Popularity'].pct_change() * 100
    df['Moving_Avg'] = df['Popularity'].rolling(window=12).mean()
    df['Moving_STD'] = df['Popularity'].rolling(window=12).std()

    # 6. Classify Growth Phases (Using NumPy Conditional Logic)
    # Thresholds: Growth > 5%, Decline < -5%
    conditions = [
        (df['Growth_Rate'] > 5),
        (df['Growth_Rate'] < -5),
        (df['Growth_Rate'].notnull())
    ]
    choices = ['Growth', 'Decline', 'Stable']
    df['Phase'] = np.select(conditions, choices, default="N/A")

    # 7. Statistical Summary & Key Metrics
    summary = df['Popularity'].describe()
    initial_pop = df['Popularity'].iloc[0]
    final_pop = df['Popularity'].iloc[-1]
    overall_growth = ((final_pop - initial_pop) / initial_pop) * 100
    phase_counts = df['Phase'].value_counts()

    # 8. Final Output
    print(f"Assigned Language: {assigned_language}")
    print("-" * 40)
    print("\nMain Analysis DataFrame (First 5 Rows):")
    print(df.head())

    print("\nStatistical Summary Table:")
    print(summary)

    print("\nGrowth Phase Counts:")
    print(phase_counts)

    print("\nKey Performance Metrics:")
    print(f"- Initial Popularity: {initial_pop:.2f}")
    print(f"- Final Popularity: {final_pop:.2f}")
    print(f"- Overall Growth Percentage: {overall_growth:.2f}%")
    print(f"- Total Periods Analyzed: {len(df)}")

except FileNotFoundError:
    print(f"ERROR: The file '{filename}' was not found.")
    print("Please ensure you have dragged the CSV file into your VS Code sidebar.")
except Exception as e:
    print(f"An error occurred: {e}")

Assigned Language: React Worldwide(%)
----------------------------------------

Main Analysis DataFrame (First 5 Rows):
       Month  Popularity  Growth_Rate  Moving_Avg  Moving_STD    Phase
0 2004-01-01           1          NaN         NaN         NaN      N/A
1 2004-02-01           2        100.0         NaN         NaN   Growth
2 2004-03-01           2          0.0         NaN         NaN   Stable
3 2004-04-01           1        -50.0         NaN         NaN  Decline
4 2004-05-01           2        100.0         NaN         NaN   Growth

Statistical Summary Table:
count    249.000000
mean      25.883534
std       32.518210
min        1.000000
25%        1.000000
50%        2.000000
75%       50.000000
max      100.000000
Name: Popularity, dtype: float64

Growth Phase Counts:
Phase
Stable     170
Growth      53
Decline     25
N/A          1
Name: count, dtype: int64

Key Performance Metrics:
- Initial Popularity: 1.00
- Final Popularity: 85.00
- Overall Growth Percentage: 8400.00%
- 

In [2]:
import pandas as pd
import numpy as np

# 1. Identification and Configuration
student_id = "TUPM-24-2017" #
last_three_digits = 17 # Derived from student ID
filename = 'Most Popular Programming Languages.csv' # Verified from environment

try:
    # 2. Data Loading and Cleaning
    df_raw = pd.read_csv(filename)
    date_col = df_raw.columns[0]
    df_raw[date_col] = pd.to_datetime(df_raw[date_col]) # Convert to datetime

    # 3. Language Assignment (Sorted Alphabetically)
    languages = sorted([col for col in df_raw.columns if col != date_col])
    assigned_index = last_three_digits % len(languages)
    assigned_language = languages[assigned_index]

    # 4. Core Calculations
    df = df_raw[[date_col, assigned_language]].copy()
    df.columns = ['Month', 'Popularity']
    
    # Growth Rate Metrics
    df['Growth_Rate'] = df['Popularity'].pct_change() * 100 #
    df['Moving_Avg'] = df['Popularity'].rolling(window=6).mean() # 6-month smoothing
    df['Moving_STD'] = df['Popularity'].rolling(window=6).std() #

    # Statistical Tendency
    growth_mean = np.mean(df['Growth_Rate'].dropna()) #
    growth_std = np.std(df['Growth_Rate'].dropna()) #

    # 5. Lifecycle Rules Definition
    # Applying rules using NumPy conditional logic
    conditions = [
        (df['Growth_Rate'] < 0) & (df['Growth_Rate'] < (-1 * growth_std)), # Decline
        (np.abs(df['Growth_Rate']) <= 1.0),                               # Maturity
        (df['Growth_Rate'] > growth_mean),                                # Growth
        (df['Growth_Rate'] > 0) & (df['Growth_Rate'] <= growth_mean)      # Introduction
    ]
    choices = ['Decline', 'Maturity', 'Growth', 'Introduction']
    df['Lifecycle_Phase'] = np.select(conditions, choices, default="Stable/Indeterminate")

    # 6. Summary and Interpretive Metrics
    phase_counts = df['Lifecycle_Phase'].value_counts()
    dominant_stage = phase_counts.idxmax()
    
    # Output Results
    print(f"Assigned Language: {assigned_language}")
    print("-" * 50)
    print("\nLifecycle Classification Table (Sample):")
    print(df[['Month', 'Popularity', 'Growth_Rate', 'Moving_Avg', 'Lifecycle_Phase']].tail(10))

    print("\n--- Summary Distribution ---")
    print(phase_counts)
    
    print(f"\nInterpretive Insight: {assigned_language} is primarily in the {dominant_stage} phase.")
    print("This implies a consistent global trajectory relative to historical volatility.")

except FileNotFoundError:
    print(f"Error: '{filename}' not found. Ensure the file is in your project directory.")

Assigned Language: React Worldwide(%)
--------------------------------------------------

Lifecycle Classification Table (Sample):
         Month  Popularity  Growth_Rate  Moving_Avg       Lifecycle_Phase
239 2023-12-01          73   -12.048193   83.333333  Stable/Indeterminate
240 2024-01-01          89    21.917808   83.500000                Growth
241 2024-02-01          98    10.112360   85.333333                Growth
242 2024-03-01          91    -7.142857   86.333333  Stable/Indeterminate
243 2024-04-01          97     6.593407   88.500000                Growth
244 2024-05-01          96    -1.030928   90.666667  Stable/Indeterminate
245 2024-06-01          87    -9.375000   93.000000  Stable/Indeterminate
246 2024-07-01          92     5.747126   93.500000                Growth
247 2024-08-01          86    -6.521739   91.500000  Stable/Indeterminate
248 2024-09-01          85    -1.162791   90.500000  Stable/Indeterminate

--- Summary Distribution ---
Lifecycle_Phase
Maturity 

In [3]:
import pandas as pd
import numpy as np

# 1. Configuration & Identification
student_id = "TUPM-24-2017"
last_three_digits = 17 
filename = 'Most Popular Programming Languages.csv'

try:
    # 2. Load and Prepare Data
    df_raw = pd.read_csv(filename)
    date_col = df_raw.columns[0]
    df_raw[date_col] = pd.to_datetime(df_raw[date_col])

    # 3. Language Selection Rule
    # Alphabetical list of languages excluding the date column
    languages = sorted([col for col in df_raw.columns if col != date_col])
    
    # First language based on student ID index
    idx1 = last_three_digits % len(languages)
    lang_a_name = languages[idx1]
    
    # Second language is the next one alphabetically (wraps to start if at end)
    idx2 = (idx1 + 1) % len(languages)
    lang_b_name = languages[idx2]

    # 4. Comparative Calculations
    data_a = df_raw[lang_a_name]
    data_b = df_raw[lang_b_name]

    # Central Tendencies
    stats = {
        'Mean_A': data_a.mean(),
        'Mean_B': data_b.mean(),
        'Std_A': data_a.std(),
        'Std_B': data_b.std(),
        'Median_A': data_a.median(),
        'Median_B': data_b.median()
    }

    # Correlation Coefficient
    correlation = np.corrcoef(data_a, data_b)[0, 1]

    # Dominance Ratio
    months_a_leads = np.sum(data_a > data_b)
    total_months = len(df_raw)
    dominance_ratio = (months_a_leads / total_months) * 100

    # Relative Performance Index (RPI)
    # Simple RPI defined as the average ratio of popularity over time
    rpi = (data_a / data_b).mean()

    # Identify Crossover Points (Months when A surpasses B)
    # We find where A > B was false in previous month but true now
    crossovers = df_raw[date_col][(data_a > data_b) & (data_a.shift(1) <= data_b.shift(1))]

    # 5. Output Summary Table
    summary_df = pd.DataFrame({
        'Metric': ['Mean', 'Std Dev', 'Correlation', 'Dominance Ratio (%)', 'RPI'],
        lang_a_name: [stats['Mean_A'], stats['Std_A'], correlation, dominance_ratio, rpi],
        lang_b_name: [stats['Mean_B'], stats['Std_B'], correlation, "N/A", "N/A"]
    })

    print(f"Assigned Languages: {lang_a_name} vs {lang_b_name}")
    print("-" * 60)
    print("\nComparative Statistics Summary:")
    print(summary_df.to_string(index=False))

    if not crossovers.empty:
        print("\nSignificant Crossover Points (A surpassed B):")
        print(crossovers.head().to_string(index=False))
    else:
        print(f"\nNo crossover points detected: {lang_a_name} or {lang_b_name} maintained dominance.")

    # 6. Interpretation
    if stats['Std_A'] < stats['Std_B']:
        print(f"\nInterpretation: {lang_a_name} demonstrates more consistent growth with lower variability.")
    else:
        print(f"\nInterpretation: {lang_b_name} demonstrates more resilient stability or consistent trends.")

except FileNotFoundError:
    print(f"Error: The file '{filename}' was not found in your directory.")
except Exception as e:
    print(f"An error occurred during analysis: {e}")

Assigned Languages: React Worldwide(%) vs Swift Worldwide(%)
------------------------------------------------------------

Comparative Statistics Summary:
             Metric  React Worldwide(%) Swift Worldwide(%)
               Mean           25.883534          30.678715
            Std Dev           32.518210          15.328697
        Correlation            0.450270            0.45027
Dominance Ratio (%)           35.742972                N/A
                RPI            0.774090                N/A

Significant Crossover Points (A surpassed B):
2017-02-01
2017-10-01
2024-03-01

Interpretation: Swift Worldwide(%) demonstrates more resilient stability or consistent trends.
